name: CI with Checkstyle

on:
  push:
    branches:
      - F1-1 # Trigger the workflow when changes are pushed to the F1 branch

jobs:
  build-and-check:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: F1  # Checkout the F1 sub-branch of main

      # Step 2: Set up JDK 17 (Fixing distribution version as per your current setup)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use JDK 17 for the build process
          distribution: 'temurin'  # Use the Temurin distribution of OpenJDK

      # Step 3: Extract git commit data
      - name: Extract git commit data
        id: commit-data 
        uses: rlespinasse/git-commit-data-action@v1.x  # Extract commit data (e.g., commit hash, author, message)

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests -e # Build the project using Maven, skipping tests to speed up the build

      # Step 5: Run JUnit tests
      - name: JUnit tests
        run: mvn test  # Run the tests using Maven


        
